#pragma once

// Tapping
#undef  TAPPING_TERM
#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS

// Auto Shift
#define AUTO_SHIFT_TIMEOUT 150
#define AUTO_SHIFT_MODIFIERS

// One Shot Keys
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

// RGB
#define RGB_MATRIX_HUE_STEP 1
#define RGB_MATRIX_SAT_STEP 16
#define RGB_MATRIX_VAL_STEP 16
#define RGB_MATRIX_SPD_STEP 16
